<?php
    $layered_navigation_dimension=explode("x",Mage::getStoreConfig('manufacturer/manufacturer_general/layered_navigation_dimension'));
    $width=30;
    $height=30;
?>
<ol>
    <?php 
        foreach ($this->getItems() as $_item): 
            $manufacturer_imge='';
        ?>
        <li>
            <?php 
                if (strtolower($this->getName())=='manufacturer'){
                    if(Mage::getStoreConfig("manufacturer/manufacturer_general/layered_navigation_enabled")==1){
                        $manufacturers=Mage::getModel('manufacturer/manufacturer')->getCollection()->addFieldToFilter('menufecturer_name',$_item->getValue())->addFieldToFilter('status',Array('eq'=>1))->load();
                        foreach ($manufacturers as $manufacturer){
                            $productModel = Mage::getModel('catalog/product');
                            $attr = $productModel->getResource()->getAttribute("manufacturer");
                            $manufacturer_name = $attr->getSource()->getOptionText($manufacturer->getMenufecturerName());
                            $manufacturer_imge=$manufacturer->getFilename();
                        }
                        if ($manufacturer_imge){
                        ?>
                        <img src="<?php echo Mage::helper('manufacturer')->getManufacturerUrlFrontend($manufacturer_name,$manufacturer_imge,'small_thumb') ?>" alt="" class="manufacturer_image" title="<?php echo $manufacturer_name; ?>" />
                        <?php }
                    }
                }
            ?>
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
                <?php else: echo $_item->getLabel() ?>
                <?php endif; ?>
            (<?php echo $_item->getCount() ?>)
        </li>
        <?php endforeach ?>
</ol>
